#!/usr/bin/env python3
"""Generate 170+ terminal commands as properly escaped JS"""
import json

def q(s):
    """Escape a string for single-quoted JS"""
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n')

def cmd(name, body):
    """Generate a JS command entry"""
    return f"  O['{name}']=function(){{return'{q(body)}';}};"

out = []

# === HELP ===
out.append(cmd("help", '  <span class="cmd">help</span> 帮助  <span class="cmd">ls</span> 列文件  <span class="cmd">cat</span> 查看  <span class="cmd">pwd</span> 路径<br>  <span class="cmd">clear</span> 清屏  <span class="cmd">mkdir</span> 建目录  <span class="cmd">touch</span> 建文件  <span class="cmd">rm</span> 删除<br>  <span class="cmd">neofetch</span> 系统  <span class="cmd">tree</span> 目录树  <span class="cmd">calc</span> 计算<br>  <span class="cmd">ps</span> 进程  <span class="cmd">free</span> 内存  <span class="cmd">df</span> 磁盘  <span class="cmd">echo</span> 输出  <span class="cmd">date</span> 日期<br>  输入 <span class="cmd">cmds</span> 查看全部170+条命令'))

# === CORE UNIX (35) ===
out.append(cmd("ls", '  <span class="path">Documents/</span>  <span class="path">Pictures/</span>  <span class="path">Music/</span>  <span class="path">Desktop/</span><br>  README.txt  todo.txt  kernel.js  boot.log'))
out.append(cmd("pwd", '  <span class="path">/home/user</span>'))
out.append(cmd("cd", '  <span class="warn">模拟目录切换: '+arg+'/</span>', ))
out.append(cmd("cat", '  <span class="err">用法: cat <文件路径></span>', ))
out.append(cmd("mkdir", '  <span class="err">用法: mkdir <目录名></span>'))
out.append(cmd("touch", '  <span class="err">用法: touch <文件名></span>'))
out.append(cmd("rm", '  <span class="err">用法: rm <路径></span>'))
out.append(cmd("rmdir", '  <span class="err">用法: rmdir <目录路径></span>'))
out.append(cmd("echo", '  '+arg))
out.append(cmd("clear", ''))
out.append(cmd("write", '  <span class="err">用法: write <文件路径> <内容></span>'))
out.append(cmd("cp", '  <span class="warn">功能暂未实现(VFS限制)</span>'))
out.append(cmd("mv", '  <span class="warn">功能暂未实现(VFS限制)</span>'))
out.append(cmd("ln", '  <span class="warn">符号链接不受支持</span>'))
out.append(cmd("chmod", '  <span class="val">V 权限已模拟修改</span>'))
out.append(cmd("chown", '  <span class="val">V 所有者: user:staff</span>'))
out.append(cmd("find", '  <span class="path">./Documents/README.txt</span><br>  <span class="path">./Documents/todo.txt</span><br>  <span class="path">./System/kernel.js</span>'))
out.append(cmd("grep", '  <span class="warn">VFS 不支持全文搜索</span>'))
out.append(cmd("wc", '  <span class="val">42 256 2048</span>'))
out.append(cmd("sort", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("uniq", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("head", '  line 1<br>  line 2<br>  line 3<br>  <span style="color:#8b949e">...省略剩余行</span>'))
out.append(cmd("tail", '  <span style="color:#8b949e">...省略前几行</span><br>  line 98<br>  line 99<br>  line 100'))
out.append(cmd("cut", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("diff", '  <span class="info">文件相同(模拟)</span>'))
out.append(cmd("file", '  <span class="info">'+arg+': ASCII text</span>'))
out.append(cmd("which", '  <span class="path">/usr/bin/'+arg+'</span>'))
out.append(cmd("whereis", '  <span class="path">/usr/bin/'+arg+'  /usr/share/man/man1/'+arg+'.1</span>'))
out.append(cmd("type", '  <span class="info">'+arg+' 是内置命令</span>'))
out.append(cmd("tee", '  <span class="val">V 输出已复制</span>'))
out.append(cmd("tr", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("yes", '  <span class="info">y y y y y y y y ... (Ctrl+C 停止)</span>'))

# === SYSTEM INFO (17) ===
out.append(cmd("uname", '  <span class="val">FusionOS</span> 7.0 fusionos-7.0-generic x86_64'))
out.append(cmd("hostname", '  <span class="val">fusionos-desktop</span>'))
out.append(cmd("whoami", '  <span class="val">user</span>'))
out.append(cmd("who", '  <span class="val">user     pts/0        '+new Date().toLocaleString("zh-CN")+'</span>'))
out.append(cmd("id", '  <span class="val">uid=1000(user) gid=1000(user) groups=1000(user),998(wheel),997(staff)</span>'))
out.append(cmd("groups", '  <span class="val">user wheel staff</span>'))
out.append(cmd("uptime", '  <span class="val">up 2小时 35分</span>, 1 user, load avg: 0.15 0.05 0.01'))
out.append(cmd("arch", '  <span class="val">x86_64</span>'))
out.append(cmd("dmesg", '  <span style="color:#8b949e">[0.000] Kernel booting...<br>[0.012] CPU: FusionOS 7.0 x86_64<br>[0.024] Memory: 16GB available<br>[0.036] VFS mounted<br>[0.048] WM initialized<br>[1.200] Desktop ready</span>'))
out.append(cmd("lscpu", '  <span class="val">Architecture: x86_64</span><br>  CPU(s): 8<br>  Model: FusionOS Virtual CPU @ 3.2GHz'))
out.append(cmd("lsblk", '  <span class="val">NAME  MAJ:MIN  SIZE  TYPE  MOUNTPOINT</span><br>  vda   254:0    16G   disk  /'))
out.append(cmd("lspci", '  <span class="val">00:00.0  Host bridge: FusionOS<br>00:01.0  VGA controller: FusionOS Display<br>00:02.0  Network controller: FusionNet<br>00:03.0  Audio device: FusionAudio</span>'))
out.append(cmd("mount", '  <span class="val">FusionDisk on / type fusfs (rw)</span>'))
out.append(cmd("vmstat", '  <span class="val">procs  memory      swap  io  system  cpu</span><br>  r b  free  buff  cache  si  so  bi  bo  in  cs  us sy id<br>  0 0  12G  0  0  0  0  0  0  1  2  2 1 97'))
out.append(cmd("umount", '  <span class="val">V 已卸载(模拟)</span>'))
out.append(cmd("sysinfo", '  <span class="val">=== 系统信息 ===</span><br>  OS: FusionOS 7.0<br>  Kernel: fusionos-7.0<br>  CPU: Virtual x86_64 @ 3.2GHz<br>  RAM: 16GB<br>  Disk: FusionDisk 16GB<br>  Apps: '+APPS.length+'<br>  Commands: 170+'))
out.append(cmd("version", '  <span class="val">FusionOS 7.0</span> — Build 2026-06-15<br>  Kernel: fusionos-7.0-generic<br>  Shell: fusion-term 7.0<br>  Apps: '+APPS.length+'<br>  Features: 150+'))

# === NETWORK (20) ===
out.append(cmd("ping", '  <span class="err">用法: ping <地址></span>'))
out.append(cmd("curl", '  <span class="info">模拟 HTTP 请求...</span><br>  <span class="val">HTTP/1.1 200 OK</span><br>  Content-Type: text/html<br>  <span style="color:#8b949e"><html>FusionOS 7.0</html></span>'))
out.append(cmd("wget", '  <span class="info">模拟下载: '+arg+'</span><br>  <span class="val">100% [====================] 1.2MB/s   0s</span><br>  V 已保存为 index.html'))
out.append(cmd("ifconfig", '  <span class="val">eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST></span><br>  inet 192.168.1.100  netmask 255.255.255.0<br>  ether 00:1a:2b:3c:4d:5e'))
out.append(cmd("ip", '  <span class="val">1: eth0: <BROADCAST,MULTICAST,UP></span><br>  inet 192.168.1.100/24 scope global eth0'))
out.append(cmd("netstat", '  <span class="val">Proto  Local Address  Foreign Address  State</span><br>  tcp    0.0.0.0:443    0.0.0.0:*       LISTEN<br>  tcp    192.168.1.100:443  151.101.1.69:443  ESTABLISHED'))
out.append(cmd("ss", '  <span class="val">Netid  State  Recv-Q  Send-Q  Local:Port  Peer:Port</span><br>  tcp    ESTAB  0       0        192.168.1.100:443  151.101.1.69:443'))
out.append(cmd("nslookup", '  <span class="err">用法: nslookup <域名></span>'))
out.append(cmd("dig", '  <span class="info">; <<>> DiG 9.18 <<>> '+arg+'<br>;; ANSWER SECTION:<br>'+arg+'.  300  IN  A  142.250.80.46</span>'))
out.append(cmd("traceroute", '  <span class="err">用法: traceroute <地址></span>'))
out.append(cmd("ssh", '  <span class="warn">SSH 客户端功能未启用(模拟)</span>'))
out.append(cmd("ftp", '  <span class="warn">FTP 功能未启用(模拟)</span>'))
out.append(cmd("nc", '  <span class="warn">netcat 功能未启用(模拟)</span>'))
out.append(cmd("scp", '  <span class="warn">SCP 功能未启用(模拟)</span>'))
out.append(cmd("telnet", '  <span class="warn">Telnet 功能未启用(模拟)</span>'))
out.append(cmd("tcpdump", '  <span class="warn">tcpdump 需要 root 权限</span>'))
out.append(cmd("wifi", '  <span class="val">Wi-Fi 状态: 已连接 (FusionNet)</span><br>  SSID: FusionNet-5G<br>  信号强度: 92%<br>  IP: 192.168.1.100'))
out.append(cmd("speedtest", '  <span class="info">测速中...</span><br>  <span class="val">下载: 352.1 Mbps</span><br>  <span class="val">上传: 124.5 Mbps</span><br>  <span class="val">延迟: 12 ms</span>'))
out.append(cmd("route", '  <span class="val">Kernel IP routing table</span><br>  Destination  Gateway      Genmask        Iface<br>  0.0.0.0      192.168.1.1  0.0.0.0        eth0'))
out.append(cmd("arp", '  <span class="val">Address        HWaddress</span><br>  192.168.1.1    00:11:22:33:44:55'))

# === MONITORING (12) ===
out.append(cmd("ps", '  <span class="val">PID  COMMAND</span><br>  1001 fusion-wm<br>  1002 fusion-term<br>  1003 fusion-finder<br>  1004 vfs-daemon<br>  1005 notificationd'))
out.append(cmd("top", '  <span class="val">PID  USER  %CPU  %MEM  COMMAND</span><br>  1001 user  2.3   0.5   fusion-wm<br>  1002 user  0.1   0.2   fusion-term'))
out.append(cmd("free", '  <span class="val">FusionDisk 16 GB</span><br>  已用: 4.2 GB  |  可用: 11.8 GB<br>  使用率: 26.3%'))
out.append(cmd("df", '  <span class="val">文件系统       总大小     已用      可用  使用率</span><br>  FusionDisk   16.0GB    4.2GB    11.8GB    26%'))
out.append(cmd("du", '  <span class="val">4.2G  ./Documents</span><br>  <span class="val">2.1G  ./Pictures</span><br>  <span class="val">1.8G  ./Music</span><br>  <span class="val">8.1G  total</span>'))
out.append(cmd("iostat", '  <span class="val">Device  tps  kB_read/s  kB_wrtn/s</span><br>  vda     15.2  120         45'))
out.append(cmd("iotop", '  <span class="warn">iotop 需要 root 权限</span>'))
out.append(cmd("mpstat", '  <span class="val">CPU  %usr  %sys  %idle</span><br>  all  3.2   1.1   95.7'))
out.append(cmd("sensors", '  <span class="val">coretemp-isa-0000</span><br>  Core 0: +42.5C<br>  Core 1: +41.0C'))
out.append(cmd("hwinfo", '  <span class="val">CPU: FusionOS Virtual CPU @ 3.2GHz</span><br>  RAM: 16GB DDR4<br>  GPU: FusionOS Display Adapter<br>  NET: FusionNet Gigabit Ethernet'))
out.append(cmd("perf", '  <span class="val">性能评分: '+calcPerfScore()+'/10</span>'))

# === TEXT PROCESSING (10) ===
out.append(cmd("awk", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("sed", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("nl", '  <span class="val">1  line one</span><br>  <span class="val">2  line two</span><br>  <span class="val">3  line three</span>'))
out.append(cmd("fmt", '  <span class="val">V 文本已重新格式化</span>'))
out.append(cmd("strings", '  <span class="warn">VFS 不支持二进制文件</span>'))
out.append(cmd("xxd", '  <span class="warn">VFS 不支持十六进制转储</span>'))
out.append(cmd("column", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("sponge", '  <span class="warn">请在管道中使用</span>'))
out.append(cmd("split", '  <span class="val">V 模拟分割: 创建了 xaa, xab, xac</span>'))
out.append(cmd("csplit", '  <span class="val">V 模拟分割</span>'))

# === DEV TOOLS (15) ===
out.append(cmd("git", '  <span class="info">usage: git [--version] [-C path] ...</span>'))
out.append(cmd("npm", '  <span class="info">npm v10.2.0 (模拟)</span><br>  <span class="info">up to date in 1.2s</span>'))
out.append(cmd("pip", '  <span class="info">pip 24.0 from /usr/lib/python3 (模拟)</span>'))
out.append(cmd("make", '  <span class="info">make[1]: Entering directory /home/user/project</span><br>  <span class="val">gcc main.o -o main</span><br>  <span class="val">V Build complete</span>'))
out.append(cmd("gcc", '  <span class="val">V 编译成功: a.out</span>'))
out.append(cmd("python", '  <span class="info">Python 3.12.0 (FusionOS)</span>'))
out.append(cmd("node", '  <span class="info">Node.js v22.0.0 (FusionOS)</span>'))
out.append(cmd("docker", '  <span class="warn">Docker 不支持(浏览器环境)</span>'))
out.append(cmd("java", '  <span class="info">openjdk version 21.0.2 (模拟)</span>'))
out.append(cmd("ruby", '  <span class="info">ruby 3.3.0 [x86_64-fusionos]</span>'))
out.append(cmd("go", '  <span class="info">go version go1.22.0 fusionos/amd64 (模拟)</span>'))
out.append(cmd("rustc", '  <span class="info">rustc 1.77.0 (模拟)</span>'))
out.append(cmd("perl", '  <span class="info">This is perl 5, version 38 (模拟)</span>'))
out.append(cmd("php", '  <span class="info">PHP 8.3.0 (cli) (模拟)</span>'))
out.append(cmd("lua", '  <span class="info">Lua 5.4.6 (模拟)</span>'))

# === FUN (20) ===
ascii_art = r'  <pre style="color:var(--accent);font-size:7px;line-height:1"> ++++++++++++++++++++++<br>+   FusionOS 7.0     +<br>+    33 Apps Ready    +<br>+   170+ Commands     +<br>++++++++++++++++++++++</pre>'
out.append(cmd("neofetch", ascii_art))
out.append(cmd("cowsay", '  <pre style="color:#c9d1d9"> _______________<br>< FusionOS! ><br> ---------------<br>        \\   ^__^<br>         \\  (oo)\\_______<br>            (__)\\       )\\/\\<br>                ||----w |<br>                ||     ||</pre>'))
out.append(cmd("fortune", '  <span class="info">你今天会很幸运！</span>'))
out.append(cmd("banner", '  <pre style="color:var(--accent)">FUSION</pre>'))
out.append(cmd("sl", '  <pre style="color:#c9d1d9">CHOO CHOO! ==== _______<br>  _D _|  |_____/  |__[_]<br>   (_)===  |  |  \\  ||<br>  |___|   ==  ==   \\_|</pre>'))
out.append(cmd("cmatrix", '  <span style="color:#00ff00">Matrix mode activated...</span>'))
out.append(cmd("figlet", '  <pre style="color:var(--accent);font-size:10px"> _____ _   _ ____ ___ ___  _   _<br>|  ___| | | / ___|_ _/ _ \\| \\ | |<br>| |_  | | | \\___ \\| | | | |  \\| |<br>|  _| | |_| |___) | | |_| | |\\  |<br>|_|    \\___/|____/___\\___/|_| \\_|</pre>'))
out.append(cmd("nyancat", '  <pre style="color:#ff69b4">  /l,     Nyan~<br> (.. )7     Nyan~<br>  l  ~_    Nyan~<br>   "_,)    Nyan~</pre>'))
out.append(cmd("rig", '  <span class="val">身份已生成:</span><br>  姓名: 张伟<br>  地址: 北京市朝阳区100号<br>  电话: 138****5678'))
out.append(cmd("rev", '  <span class="val">'+arg.split("").reverse().join("")+'</span>'))
out.append(cmd("factor", '  <span class="val">2 3 7</span>'))
out.append(cmd("jot", '  <span class="val">1 2 3 4 5 6 7 8 9 10</span>'))
out.append(cmd("asciiquarium", '  <pre style="color:#42a5f5">   ><(((*>   <..)))><   ><(((*></pre>'))
out.append(cmd("ponysay", '  <pre style="color:#ff69b4">Unicorn: FusionOS is magic!</pre>'))
out.append(cmd("lolcat", '  <span style="color:#ff6b6b">R</span><span style="color:#ffd93d">a</span><span style="color:#6bcb77">i</span><span style="color:#4d96ff">n</span><span style="color:#ff6b6b">b</span><span style="color:#ffd93d">o</span><span style="color:#6bcb77">w</span>'))
out.append(cmd("espeak", '  <span class="warn">TTS 功能不可用(浏览器限制)</span>'))
out.append(cmd("matrix", '  <span style="color:#00ff00">Escape the Matrix. Enter FusionOS.</span>'))
out.append(cmd("rickroll", '  <span class="warn">Never gonna give you up, Never gonna let you down</span>'))
out.append(cmd("hack", '  <pre style="color:#00ff00;font-size:10px">[+] Initializing hack module...<br>[+] Bypassing firewall... OK<br>[+] Accessing target... 192.168.1.1<br>[-] ERROR: This is a simulation</pre>'))

# === MATH & CALC (10) ===
out.append(cmd("calc", '  <span class="err">用法: calc <表达式></span>'))
out.append(cmd("bc", '  <span class="val">42</span>'))
out.append(cmd("expr", '  <span class="val">42</span>'))
out.append(cmd("units", '  <span class="warn">请使用"单位换算"应用</span>'))
out.append(cmd("seq", '  <span class="val">1 2 3 4 5 6 7 8 9 10</span>'))
out.append(cmd("numfmt", '  <span class="val">1,024</span>'))
out.append(cmd("shuf", '  <span class="val">7 3 9 1 5 8 2 4 6 10</span>'))
out.append(cmd("rand", '  <span class="val">42</span>'))
out.append(cmd("prime", '  <span class="val">是质数</span>'))
out.append(cmd("fib", '  <span class="val">0 1 1 2 3 5 8 13 21 34</span>'))

# === CRYPTO (10) ===
out.append(cmd("md5sum", '  <span class="val">d41d8cd98f00b204e9800998ecf8427e  -</span>'))
out.append(cmd("sha256sum", '  <span class="val">e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -</span>'))
out.append(cmd("base64", '  <span class="val">'+btoa(unescape(encodeURIComponent(arg||"FusionOS")))+'</span>'))
out.append(cmd("openssl", '  <span class="warn">OpenSSL 功能不可用(浏览器限制)</span>'))
out.append(cmd("gpg", '  <span class="warn">GPG 功能不可用(浏览器限制)</span>'))
out.append(cmd("ssh-keygen", '  <span class="val">V 已生成密钥对:</span><br>  ~/.ssh/id_rsa<br>  ~/.ssh/id_rsa.pub<br>  <span style="color:#8b949e">指纹: SHA256:abc123...</span>'))
out.append(cmd("passwd", '  <span class="info">更改密码功能已模拟</span><br>  <span class="val">V 密码已更新</span>'))
out.append(cmd("chroot", '  <span class="warn">chroot 需要 root 权限</span>'))
out.append(cmd("sudo", '  <span class="info">'+arg+' (已以超级用户身份模拟执行)</span>'))
out.append(cmd("su", '  <span class="info">已切换为 root (模拟)</span>'))

# === FILE OPS (10) ===
out.append(cmd("tar", '  <span class="val">V 已创建归档: archive.tar</span>'))
out.append(cmd("gzip", '  <span class="val">V 已压缩: '+arg+'.gz</span>'))
out.append(cmd("bzip2", '  <span class="val">V 已压缩: '+arg+'.bz2</span>'))
out.append(cmd("zip", '  <span class="val">V 已打包: archive.zip</span>'))
out.append(cmd("unzip", '  <span class="val">V 已解压到当前目录</span>'))
out.append(cmd("dd", '  <span class="val">V 模拟写入完成<br>8+0 records in<br>8+0 records out</span>'))
out.append(cmd("sync", '  <span class="val">V 已同步磁盘缓存</span>'))
out.append(cmd("stat", '  <span class="val">File: '+arg+'<br>Size: 4096<br>Access: (0644/-rw-r--r--)</span>'))
out.append(cmd("realpath", '  <span class="path">/home/user/'+arg+'</span>'))
out.append(cmd("mktemp", '  <span class="path">/tmp/tmp.x9Kf3z</span>'))

# === DATABASE (5) ===
out.append(cmd("sqlite3", '  <span class="info">SQLite version 3.45.0 (模拟)</span>'))
out.append(cmd("redis-cli", '  <span class="info">redis 127.0.0.1:6379> PONG</span>'))
out.append(cmd("mysql", '  <span class="info">MySQL 8.0 (模拟) - 连接本地数据库</span>'))
out.append(cmd("mongo", '  <span class="info">MongoDB shell 7.0 (模拟)</span>'))
out.append(cmd("psql", '  <span class="info">psql (PostgreSQL) 16.0 (模拟)</span>'))

# === FUSIONOS SPECIFIC (18) ===
out.append(cmd("notify", '  <span class="val">V 通知已发送</span>'))
out.append(cmd("open", '  <span class="err">用法: open <应用名></span>'))
out.append(cmd("wallpaper", '  <span class="val">V 壁纸已随机切换</span>'))
out.append(cmd("save", '  <span class="val">V 系统状态已保存</span>'))
out.append(cmd("reset", '  <span class="err">用法: reset confirm (清除所有数据)</span>'))
out.append(cmd("info", '  <span class="val">FusionOS 7.0</span><br>  '+APPS.length+' 个应用 | 170+ 终端命令'))
out.append(cmd("debug", '  <span class="val">VFS keys: </span>'+JSON.stringify(Object.keys(VFS))))
out.append(cmd("credits", '  <span class="val">FusionOS 7.0 - Credits</span><br>  开发者: Fusion Team<br>  图标: 自定义 SVG<br>  技术栈: HTML/CSS/JS (零依赖)'))
out.append(cmd("license", '  <span class="info">FusionOS 7.0 License</span><br>  MIT License (模拟)<br>  Copyright 2026 FusionOS'))
out.append(cmd("changelog", '  <span class="val">v7.0 - 2026-06-15</span><br>  + 15 个新应用<br>  + 3 个游戏<br>  + 170+ 终端命令<br>  + 100 个系统功能'))
out.append(cmd("update", '  <span class="val">V 已是最新版本 (7.0)</span>'))
out.append(cmd("donate", '  <span style="color:#ffd700">Star 感谢支持！FusionOS 永远免费。</span>'))
out.append(cmd("cmds", '  <span class="info">共 172 条命令，输入 help-cat <类别> 查看:</span><br>  core · sysinfo · net · monitor · text · dev · fun · math · crypto · file · db · fusion'))
out.append(cmd("help-cat", '  <span class="val">core:</span> ls cd pwd cat mkdir touch rm rmdir echo clear write<br>  <span class="val">sysinfo:</span> uname hostname whoami who id groups<br>  <span class="val">net:</span> ping curl wget ifconfig ip netstat<br>  <span class="val">monitor:</span> ps top free df du iostat<br>  <span class="val">dev:</span> git npm pip make gcc python node<br>  <span class="val">fun:</span> neofetch cowsay fortune banner sl figlet<br>  <span class="val">fusion:</span> notify open wallpaper save reset info'))
out.append(cmd("fetch", '  <span class="val">'+getGreeting()+'！FusionOS 7.0 已就绪</span>'))
out.append(cmd("quote", '  <span class="info">代码就是诗</span>'))
out.append(cmd("joke", '  <span class="info">为什么程序员不喜欢户外活动？太多bug了！</span>'))
out.append(cmd("thanks", '  <span class="info">感谢使用 FusionOS 7.0!</span>'))

# === MISC (8) ===
out.append(cmd("date", '  '+new Date().toLocaleString("zh-CN")))
out.append(cmd("time", '  <span class="val">实际使用: 0.02s user, 0.01s system</span>'))
out.append(cmd("man", '  <span class="info">'+arg.toUpperCase()+'(1)</span><br>  <span style="color:#8b949e">手册不可用。尝试: help</span>'))
out.append(cmd("alias", '  <span class="val">alias ll="ls -la"<br>alias la="ls -A"<br>alias ..="cd .."</span>'))
out.append(cmd("export", '  <span class="val">HOME=/home/user<br>PATH=/usr/bin:/bin<br>USER=user<br>SHELL=fusion-term</span>'))
out.append(cmd("env", '  <span class="val">HOME=/home/user<br>PATH=/usr/bin:/bin<br>USER=user<br>FUSION_VERSION=7.0</span>'))
out.append(cmd("history", '  <span class="val">1  ls</span><br>  <span class="val">2  pwd</span><br>  <span class="val">3  neofetch</span><br>  <span class="val">4  '+cmd+'</span>'))
out.append(cmd("printenv", '  <span class="val">HOME=/home/user<br>USER=user<br>SHELL=fusion-term</span>'))

# === SYSTEM ACTIONS (5) ===
out.append(cmd("logout", '  <span class="val">正在注销...</span>'))
out.append(cmd("shutdown", '  <span class="val">正在关机...</span>'))
out.append(cmd("reboot", '  <span class="val">正在重启...</span>'))
out.append(cmd("lock", '  <span class="val">V 屏幕已锁定</span>'))
out.append(cmd("exit", '  <span class="val">再见！</span>'))

print(f"Total commands: {len(out)}")

# Write the final JS
with open('/Users/murderdrones/WorkBuddy/2026-06-15-12-25-08/term_cmds.js', 'w') as f:
    f.write("function termExec(cmd,id){\n")
    f.write("  var tl=document.getElementById('tl-'+id);if(!tl)return;\n")
    f.write("  var row=document.createElement('div');row.className='line';\n")
    f.write("  row.innerHTML='<span class=\"prompt\">\\u276f </span><span style=\"color:#c9d1d9\">'+escHtml(cmd)+'</span>';\n")
    f.write("  tl.appendChild(row);\n")
    f.write("  var out=document.createElement('div');out.className='line';\n")
    f.write("  var parts=cmd.split(/\\s+/),c=parts[0].toLowerCase(),arg=parts.slice(1).join(' ');\n")
    f.write("  var O={};\n")
    for cmd_entry in out:
        f.write(cmd_entry + '\n')
    f.write("  var fn=O[c];\n")
    f.write("  out.innerHTML=fn?fn():'  <span class=\"err\">'+c+': 命令未找到</span><br>  <span style=\"color:#8b949e\">输入 help 查看命令，输入 cmds 查看所有172条命令</span>';\n")
    f.write("  tl.appendChild(out);var term=document.getElementById('term-'+id);if(term)term.scrollTop=term.scrollHeight;\n")
    f.write("}\n")

print("term_cmds.js written successfully")
